spring:
  redis:
    host: 192.168.126.128:6379
    password:
    timeout: 600
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.126.128:3306/rbac?useUnicode=true&characterEncoding=utf-8&serverTimeZone=GMT
    username: root
    password: admin


refreshTokenExpireTime: 600
accessTokenExpireTime: 600

logging:
  level.com.springboot.demo.shiro_redis_token.mapper: debug