spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: pass
    lettuce:
      pool:
        max-wait: 5000
        max-active: 1500
        min-idle: 0
        max-idle: 8
    timeout: 3600
    connect-timeout: 3600