spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sso_user
    password: Sso_fuhu_dev
    url: jdbc:mysql://172.17.10.33:13306/abcd_rbac
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1